### ISSUE TITLE
please add

### ISSUE THREAD

**Issue by BrowseSky** [codingtuto/Coding-UI#15]
Please add this method
very useful for this project
https://bloginoobs.blogspot.com/2019/11/how-to-add-google-rich-snippets-in.html

please add description
https://link.browsesky.com/2023/05/coding-ui-blogger-template.html

**Comment by BrowseSky** [comment]
please fix
  <link expr:href='data:blog.url' hreflang='x-default' rel='alternate'/>
https://support.google.com/webmasters/thread/217405910/google-search-not-show-blog

**Comment by codingtuto** [comment]
Done added✅
